// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HotelStateService_CheckAvailability_FullMethodName = "/hotelagent.HotelStateService/CheckAvailability"
	HotelStateService_InitiateCheckout_FullMethodName  = "/hotelagent.HotelStateService/InitiateCheckout"
)

// HotelStateServiceClient is the client API for HotelStateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HotelStateServiceClient interface {
	CheckAvailability(ctx context.Context, in *AvailabilityRequest, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	InitiateCheckout(ctx context.Context, in *CheckoutRequest, opts ...grpc.CallOption) (*CheckoutResponse, error)
}

type hotelStateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHotelStateServiceClient(cc grpc.ClientConnInterface) HotelStateServiceClient {
	return &hotelStateServiceClient{cc}
}

func (c *hotelStateServiceClient) CheckAvailability(ctx context.Context, in *AvailabilityRequest, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, HotelStateService_CheckAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotelStateServiceClient) InitiateCheckout(ctx context.Context, in *CheckoutRequest, opts ...grpc.CallOption) (*CheckoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckoutResponse)
	err := c.cc.Invoke(ctx, HotelStateService_InitiateCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HotelStateServiceServer is the server API for HotelStateService service.
// All implementations must embed UnimplementedHotelStateServiceServer
// for forward compatibility.
type HotelStateServiceServer interface {
	CheckAvailability(context.Context, *AvailabilityRequest) (*AvailabilityResponse, error)
	InitiateCheckout(context.Context, *CheckoutRequest) (*CheckoutResponse, error)
	mustEmbedUnimplementedHotelStateServiceServer()
}

// UnimplementedHotelStateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHotelStateServiceServer struct{}

func (UnimplementedHotelStateServiceServer) CheckAvailability(context.Context, *AvailabilityRequest) (*AvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAvailability not implemented")
}
func (UnimplementedHotelStateServiceServer) InitiateCheckout(context.Context, *CheckoutRequest) (*CheckoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateCheckout not implemented")
}
func (UnimplementedHotelStateServiceServer) mustEmbedUnimplementedHotelStateServiceServer() {}
func (UnimplementedHotelStateServiceServer) testEmbeddedByValue()                           {}

// UnsafeHotelStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HotelStateServiceServer will
// result in compilation errors.
type UnsafeHotelStateServiceServer interface {
	mustEmbedUnimplementedHotelStateServiceServer()
}

func RegisterHotelStateServiceServer(s grpc.ServiceRegistrar, srv HotelStateServiceServer) {
	// If the following call panics, it indicates UnimplementedHotelStateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HotelStateService_ServiceDesc, srv)
}

func _HotelStateService_CheckAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelStateServiceServer).CheckAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HotelStateService_CheckAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelStateServiceServer).CheckAvailability(ctx, req.(*AvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HotelStateService_InitiateCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelStateServiceServer).InitiateCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HotelStateService_InitiateCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelStateServiceServer).InitiateCheckout(ctx, req.(*CheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HotelStateService_ServiceDesc is the grpc.ServiceDesc for HotelStateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HotelStateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hotelagent.HotelStateService",
	HandlerType: (*HotelStateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAvailability",
			Handler:    _HotelStateService_CheckAvailability_Handler,
		},
		{
			MethodName: "InitiateCheckout",
			Handler:    _HotelStateService_InitiateCheckout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
