# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HotelStateServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckAvailability = channel.unary_unary(
                '/hotelagent.HotelStateService/CheckAvailability',
                request_serializer=service__pb2.AvailabilityRequest.SerializeToString,
                response_deserializer=service__pb2.AvailabilityResponse.FromString,
                _registered_method=True)
        self.InitiateCheckout = channel.unary_unary(
                '/hotelagent.HotelStateService/InitiateCheckout',
                request_serializer=service__pb2.CheckoutRequest.SerializeToString,
                response_deserializer=service__pb2.CheckoutResponse.FromString,
                _registered_method=True)


class HotelStateServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CheckAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitiateCheckout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HotelStateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailability,
                    request_deserializer=service__pb2.AvailabilityRequest.FromString,
                    response_serializer=service__pb2.AvailabilityResponse.SerializeToString,
            ),
            'InitiateCheckout': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateCheckout,
                    request_deserializer=service__pb2.CheckoutRequest.FromString,
                    response_serializer=service__pb2.CheckoutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hotelagent.HotelStateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hotelagent.HotelStateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HotelStateService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotelagent.HotelStateService/CheckAvailability',
            service__pb2.AvailabilityRequest.SerializeToString,
            service__pb2.AvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitiateCheckout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotelagent.HotelStateService/InitiateCheckout',
            service__pb2.CheckoutRequest.SerializeToString,
            service__pb2.CheckoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentServiceStub:
    """-----------------------------------------------------------------
    Agent Service (Implemented by Python, Called by Go)
    -----------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessTranscript = channel.unary_stream(
                '/hotelagent.AgentService/ProcessTranscript',
                request_serializer=service__pb2.TranscriptRequest.SerializeToString,
                response_deserializer=service__pb2.AgentResponse.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """-----------------------------------------------------------------
    Agent Service (Implemented by Python, Called by Go)
    -----------------------------------------------------------------
    """

    def ProcessTranscript(self, request, context):
        """Streams agent responses back to Go as they are generated
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessTranscript': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessTranscript,
                    request_deserializer=service__pb2.TranscriptRequest.FromString,
                    response_serializer=service__pb2.AgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hotelagent.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hotelagent.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """-----------------------------------------------------------------
    Agent Service (Implemented by Python, Called by Go)
    -----------------------------------------------------------------
    """

    @staticmethod
    def ProcessTranscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hotelagent.AgentService/ProcessTranscript',
            service__pb2.TranscriptRequest.SerializeToString,
            service__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
