# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\nhotelagent\"(\n\x13\x41vailabilityRequest\x12\x11\n\troom_type\x18\x01 \x01(\t\"\\\n\x14\x41vailabilityResponse\x12\x14\n\x0cis_available\x18\x01 \x01(\x08\x12\x17\n\x0f\x61vailable_count\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x01(\t\"H\n\x0f\x43heckoutRequest\x12\x12\n\nguest_name\x18\x01 \x01(\t\x12\x11\n\troom_type\x18\x02 \x01(\t\x12\x0e\n\x06nights\x18\x03 \x01(\x05\"R\n\x10\x43heckoutResponse\x12\x13\n\x0binvoice_url\x18\x01 \x01(\t\x12\x12\n\ninvoice_id\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\";\n\x11TranscriptRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\ntranscript\x18\x02 \x01(\t\"4\n\rAgentResponse\x12\x12\n\ntext_chunk\x18\x01 \x01(\t\x12\x0f\n\x07is_done\x18\x02 \x01(\x08\x32\xba\x01\n\x11HotelStateService\x12V\n\x11\x43heckAvailability\x12\x1f.hotelagent.AvailabilityRequest\x1a .hotelagent.AvailabilityResponse\x12M\n\x10InitiateCheckout\x12\x1b.hotelagent.CheckoutRequest\x1a\x1c.hotelagent.CheckoutResponse2_\n\x0c\x41gentService\x12O\n\x11ProcessTranscript\x12\x1d.hotelagent.TranscriptRequest\x1a\x19.hotelagent.AgentResponse0\x01\x42,Z*github.com/hotel-voice-agent/gateway/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/hotel-voice-agent/gateway/proto'
  _globals['_AVAILABILITYREQUEST']._serialized_start=29
  _globals['_AVAILABILITYREQUEST']._serialized_end=69
  _globals['_AVAILABILITYRESPONSE']._serialized_start=71
  _globals['_AVAILABILITYRESPONSE']._serialized_end=163
  _globals['_CHECKOUTREQUEST']._serialized_start=165
  _globals['_CHECKOUTREQUEST']._serialized_end=237
  _globals['_CHECKOUTRESPONSE']._serialized_start=239
  _globals['_CHECKOUTRESPONSE']._serialized_end=321
  _globals['_TRANSCRIPTREQUEST']._serialized_start=323
  _globals['_TRANSCRIPTREQUEST']._serialized_end=382
  _globals['_AGENTRESPONSE']._serialized_start=384
  _globals['_AGENTRESPONSE']._serialized_end=436
  _globals['_HOTELSTATESERVICE']._serialized_start=439
  _globals['_HOTELSTATESERVICE']._serialized_end=625
  _globals['_AGENTSERVICE']._serialized_start=627
  _globals['_AGENTSERVICE']._serialized_end=722
# @@protoc_insertion_point(module_scope)
